version: '3.9'

services:

  vlm-ui-staging:
    container_name: vlm-ui-staging
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - '8180:8180'
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
 default:
  external:
   name: proxy
