version: '3.7'

services:

  vlm-ui:
    container_name: vlm-ui
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8080:8080'

networks:
 default:
  external:
   name: proxy
